{%- if cookiecutter.use_docker == 'yes' %}
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: {{ cookiecutter.project_slug }}:latest
    container_name: {{ cookiecutter.project_slug }}
    restart: unless-stopped
    environment:
      - ENV=production
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
{%- endif %}